"""Central configuration for SAR training, datasets, and model defaults."""

from pathlib import Path

DATA_ROOT = Path(".")

RAW_IMAGE_DIR = DATA_ROOT / "Airport_Dataset_v0_images"
RAW_LABEL_DIR = DATA_ROOT / "Airport_Dataset_v0_labels"

SPLIT_OUTPUT_DIR = DATA_ROOT / "dataset"
TRAIN_IMAGE_DIR = SPLIT_OUTPUT_DIR / "train" / "images"
TRAIN_LABEL_DIR = SPLIT_OUTPUT_DIR / "train" / "labels"
VAL_IMAGE_DIR = SPLIT_OUTPUT_DIR / "val" / "images"
VAL_LABEL_DIR = SPLIT_OUTPUT_DIR / "val" / "labels"
TEST_IMAGE_DIR = SPLIT_OUTPUT_DIR / "test" / "images"
TEST_LABEL_DIR = SPLIT_OUTPUT_DIR / "test" / "labels"

CHECKPOINT_ROOT = DATA_ROOT / "checkpoints"
MAE_OUTPUT_DIR = CHECKPOINT_ROOT / "mae"
SIMCLR_OUTPUT_DIR = CHECKPOINT_ROOT / "simclr"
DETECTION_OUTPUT_DIR = CHECKPOINT_ROOT / "detection"

TRAIN_SPLIT_RATIO = 0.7
VAL_SPLIT_RATIO = 0.2
TEST_SPLIT_RATIO = 0.1
DATASET_SPLIT_SEED = 43
RATIO_TOLERANCE = 1e-6

SAR_NORMALIZE_MEAN = (0.5, 0.5, 0.5)
SAR_NORMALIZE_STD = (0.5, 0.5, 0.5)

DEFAULT_IMG_SIZE = 224
DEFAULT_NUM_WORKERS = 4

VIT_PATCH_SIZE = 16
VIT_EMBED_DIM = 192
VIT_DEPTH = 12
VIT_NUM_HEADS = 3
VIT_MLP_RATIO = 4.0
VIT_DROPOUT = 0.0

MAE_MASK_RATIO = 0.75
MAE_DECODER_UPSCALE_IMG_SIZE = 512
MAE_STANDARD_DECODER_EMBED_DIM = 128
MAE_STANDARD_DECODER_DEPTH = 4
MAE_STANDARD_DECODER_HEADS = 4
MAE_LARGE_DECODER_EMBED_DIM = 256
MAE_LARGE_DECODER_DEPTH = 8
MAE_LARGE_DECODER_HEADS = 8
MAE_BATCH_SIZE = 32
MAE_NUM_EPOCHS = 300
MAE_LR = 1.5e-4
MAE_WEIGHT_DECAY = 0.05
MAE_SAVE_EVERY = 50
MAE_ADAMW_BETAS = (0.9, 0.95)

SIMCLR_PROJECTION_DIM = 128
SIMCLR_PROJECTION_HIDDEN_DIM = 512
SIMCLR_TEMPERATURE = 0.5
SIMCLR_BATCH_SIZE = 32
SIMCLR_NUM_EPOCHS = 200
SIMCLR_LR = 3e-4
SIMCLR_WEIGHT_DECAY = 1e-4
SIMCLR_SAVE_EVERY = 50
SIMCLR_ADAMW_BETAS = (0.9, 0.999)

DETECTION_NUM_CLASSES = 1
DETECTION_NUM_QUERIES = 100
DETECTION_HIDDEN_DIM = 256
DETECTION_NUM_HEADS = 8
DETECTION_DECODER_LAYERS = 6
DETECTION_DIM_FEEDFORWARD = 1024
DETECTION_DROPOUT = 0.1
DETECTION_BATCH_SIZE = 8
DETECTION_NUM_EPOCHS = 100
DETECTION_LR = 1e-4
DETECTION_WEIGHT_DECAY = 1e-4
DETECTION_FREEZE_ENCODER_EPOCHS = 0
DETECTION_SAVE_EVERY = 10
DETECTION_ADAMW_BETAS = (0.9, 0.999)
DETECTION_GRAD_CLIP_NORM = 1.0
DETECTION_COST_CLASS = 1.0
DETECTION_COST_BBOX = 5.0
DETECTION_COST_GIOU = 2.0
DETECTION_LOSS_WEIGHT_BBOX = 5.0
DETECTION_LOSS_WEIGHT_GIOU = 2.0

LOG_SCALAR_EVERY = 10
LOG_IMAGE_EVERY = 100
COSINE_ETA_MIN_RATIO = 0.01

